### ISSUE TITLE
Multiple requests to the same route causes invalid status codes to appear

### ISSUE THREAD

**Issue by FaizanAhmedSP707** [TomStrong/DevOpsAssessment#33] opened 2023-10-18 16:11 UTC
Problem Description
=============
If a request to the same route is made, one after the other, without changing the route to point at a different page, will cause a '404'
error code to be returned to the browser, which is really strange. It does not matter whether the request is made to the home page
('/', where "Hello World" is currently being displayed for the time-being), or the page where you can view all the added POIs to the
MongoDB database, which is the '/pois/allPois' route.

This is really strange, as requests to the same web page on a typical website, do not throw out a 404 error message for each request made after the first one. This issue may be due to a configuration issue, or something else that I'm not aware of. Keep in
mind that the 404 error code commonly occurs when trying to view all POIs, with some strange characteristics also for the home
page. Below are some screenshots showing what happens with the RESTer Plugin, as well as what happens when I normally access
the app using the cloud app's domain name:

------------------------------------------------------------------------------------------------------------------------------------------------

Screenshot from accessing the app through a browser
===============
(first attempt to access the website):
![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/075565ee-cd1b-49ab-a94e-98a5b733e594)

(third attempt to access the website, the second attempt showed the same screen as the first one):
![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/b4243acf-bbd3-4265-8108-2c0c320c3e2b)

------------------------------------------------------------------------------------------------------------------------------------------------

Screenshot from RESTER
================
(attempt to view all POIs when accessing the route for the first time):
![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/7b3e184f-a8c9-4609-bc80-d2b5087f04e0)

(4th attempt to view all POIs, the 2nd & 3rd attempts both show the screen above):
![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/709472b9-eeb4-4d28-b816-2aa063d6eaa2)

----------------------------------------------------------------------------------------------------------------------------------------------

Please have a look and let everyone know if this is really a bug or some strange quirk. Thank you.

**Comment by TomStrong** [comment] 2023-10-18 18:30
NGINX seems to be the cause of the problem. Looking further into it to see how to resolve it

**Comment by TomStrong** [comment] 2023-10-18 22:07
Currently believe this can be fixed by increasing the worker connections for NGINX but NGINX Proxy Manager makes this hard to implement and test.

**Comment by TomStrong** [comment] 2023-10-18 22:16
Managed to increase the worker connections. This has not fixed it. Need to figure out why it is falling back to the local files on the server instead of serving the app from docker.

**Comment by TomStrong** [comment] 2023-10-23 19:00
Shelving this issue for now, I will remove and reconfigure NGINX later, this should fix the issue.

**Comment by TomStrong** [comment] 2023-11-01 00:30
I have setup NGINX again manually, this has fixed the issue.

**Closed by TomStrong** 2023-11-01 00:30 UTC
Labels: bug, help wanted, Azure
